name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install check
      run: sudo apt install check     
    - name: install valgrind
      run: sudo apt install valgrind
    - name: make
      run: make
    - name: make valgrind-test
      run: make valgrind-test
